version = 1

test_patterns = ["mycodo/tests/**"]

exclude_patterns = [
    "databases/alembic/versions/**",
    "docker/**",
    "install/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"