language: python
os: linux
dist: bionic
python:
  - "3.7"
before_install:
  - sudo bash mycodo/scripts/upgrade_commands.sh update-apt
  - sudo apt-get install -y libatlas-base-dev libboost-python-dev gawk git libffi-dev libi2c-dev nginx python3-dev python3-numpy sqlite3 swig
  - sudo bash mycodo/scripts/upgrade_commands.sh update-packages
  - pip install --upgrade pip webtest
  - git clone --recursive https://github.com/WiringPi/WiringPi-Python.git && cd WiringPi-Python && git submodule update --init && cd WiringPi && ./build && cd ../..
  - sudo bash mycodo/scripts/upgrade_commands.sh build-pigpiod
  - wget https://dl.influxdata.com/influxdb/releases/influxdb_1.8.0_amd64.deb && sudo dpkg -i influxdb_1.8.0_amd64.deb
  - sudo service influxdb start && sleep 2
  - sudo bash mycodo/scripts/upgrade_commands.sh update-influxdb-db-user
  - sudo useradd -M mycodo
  - export PATH=/usr/bin:$PATH
install:
  - whereis python
  - sed -i '/picamera/d' install/requirements-rpi.txt
  - pip3 install --upgrade -r install/requirements.txt
  - pip3 install --upgrade -r install/requirements-rpi.txt
  - pip3 install --upgrade -r install/requirements-testing.txt
  - sudo bash mycodo/scripts/upgrade_commands.sh setup-virtualenv
  - sudo bash mycodo/scripts/upgrade_commands.sh update-pip3-packages
  - sudo bash mycodo/scripts/upgrade_commands.sh ssl-certs-generate
  - sudo bash mycodo/scripts/upgrade_commands.sh compile-translations
  - sudo bash mycodo/scripts/upgrade_commands.sh generate-widget-html
  - cd mycodo && sudo ../env/bin/gunicorn --bind 127.0.0.1:8080 start_flask_ui:app &
  - sleep 5
  - wget --quiet --no-check-certificate -p http://127.0.0.1:8080 -O /dev/null
  - env/bin/python mycodo/scripts/generate_manual_inputs_by_measure.py
  - env/bin/python mycodo/scripts/generate_manual_inputs.py
  - env/bin/python mycodo/scripts/generate_manual_outputs.py
  - env/bin/python mycodo/scripts/generate_manual_functions.py
  - env/bin/python mycodo/scripts/generate_manual_widgets.py
script:
  - cd mycodo && pytest -W ignore::DeprecationWarning -s tests/software_tests
