language: python
os: linux
dist: xenial
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libatlas-base-dev libboost-python-dev gawk git libav-tools libffi-dev libi2c-dev nginx python3 python3-dev python3-numpy sqlite3 swig
  - pip install --upgrade pip webtest
  - sudo bash mycodo/scripts/upgrade_commands.sh install-wiringpi
  - sudo bash mycodo/scripts/upgrade_commands.sh build-pigpiod
  - sudo bash mycodo/scripts/upgrade_commands.sh update-influxdb
  - sleep 2
  - sudo bash mycodo/scripts/upgrade_commands.sh update-influxdb-db-user
  - export PATH=/usr/bin:$PATH
install:
  - sed -i '/picamera/d' install/requirements-rpi.txt
  - pip3 install --upgrade -r install/requirements.txt
  - pip3 install --upgrade -r install/requirements-rpi.txt
  - pip3 install --upgrade -r install/requirements-testing.txt
script:
  - cd mycodo && pytest -W ignore::DeprecationWarning -s tests/software_tests
