language: python
os: linux
dist: bionic
python:
  - "3.7"
before_install:
  - sudo bash mycodo/scripts/upgrade_commands.sh update-apt
  - sudo apt-get install -y libatlas-base-dev libboost-python-dev gawk git libffi-dev libi2c-dev nginx python3-dev python3-numpy sqlite3 swig
  - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -g redoc-cli
  - sudo npm install -g npx
  - sudo bash mycodo/scripts/upgrade_commands.sh update-packages
  - git clone --recursive https://github.com/WiringPi/WiringPi-Python.git && cd WiringPi-Python && git submodule update --init && cd WiringPi && ./build && cd ../..
  - sudo bash mycodo/scripts/upgrade_commands.sh build-pigpiod
  - wget https://dl.influxdata.com/influxdb/releases/influxdb_1.8.0_amd64.deb && sudo dpkg -i influxdb_1.8.0_amd64.deb
  - sudo service influxdb start && sleep 3
  - sudo bash mycodo/scripts/upgrade_commands.sh update-influxdb-db-user
  - sudo useradd -M mycodo
  - export PATH=/usr/bin:$PATH
install:
  - sudo bash mycodo/scripts/upgrade_commands.sh setup-virtualenv
  - sudo bash mycodo/scripts/upgrade_commands.sh update-pip3
  - sudo bash mycodo/scripts/upgrade_commands.sh update-pip3-packages
  - sudo bash mycodo/scripts/upgrade_commands.sh ssl-certs-generate
  - sudo bash mycodo/scripts/upgrade_commands.sh compile-translations
  - sudo bash mycodo/scripts/upgrade_commands.sh generate-widget-html
  - sudo env/bin/python mycodo/start_flask_ui.py &
  - sleep 3
  - wget --debug --no-check-certificate -p https://127.0.0.1 -O /dev/null
  - sudo bash mycodo/scripts/generate_all.sh 127.0.0.1
script:
  - cd mycodo && ../env/bin/pytest -W ignore::DeprecationWarning -s tests/software_tests
