version: "3.7"

services:

  mycodo_influxdb:
    container_name: mycodo_influxdb
    build:
      context: ../
      dockerfile: docker/influxdb/Dockerfile
    env_file:
      - 'influxdb/env.influxdb'
    volumes:
      - mycodo_influxdb:/var/lib/influxdb
      - /etc/localtime:/etc/localtime:ro  # Use timezone of the host (read-only)

  mycodo_nginx:
    container_name: mycodo_nginx
    restart: always
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - mycodo_home:/home/mycodo
      - mycodo_log:/var/log/mycodo
      - /etc/localtime:/etc/localtime:ro  # Use timezone of the host (read-only)
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mycodo_flask

  mycodo_daemon:
    container_name: mycodo_daemon
    image: app
    restart: always
    volumes:
      - mycodo_home:/home/mycodo
      - mycodo_log:/var/log/mycodo
      - /dev:/dev
      - /sys:/sys
      - /opt:/opt
      - /etc/localtime:/etc/localtime:ro  # Use timezone of the host (read-only)
    privileged: true
    command: bash -c "PYTHONPATH=/home/mycodo /home/mycodo/env/bin/python mycodo_daemon.py"
    depends_on:
      - mycodo_flask
      - mycodo_influxdb

  mycodo_flask:
    container_name: mycodo_flask
    image: app
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - mycodo_home:/home/mycodo
      - mycodo_log:/var/log/mycodo
      - /dev:/dev
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Permits container to restart itself
      - /etc/localtime:/etc/localtime:ro  # Use timezone of the host (read-only)
    privileged: true
    command: /home/mycodo/env/bin/python -m gunicorn --workers 1 --bind unix:/home/mycodo/mycodoflask.sock start_flask_ui:app
    depends_on:
      - mycodo_influxdb

#  mycodo_telegraf:
#    image: telegraf:latest
#    container_name: mycodo_telegraf
#    volumes:
#      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
#    depends_on:
#      - mycodo_influxdb
#
#  mycodo_grafana:
#    image: grafana/grafana:latest
#    container_name: mycodo_grafana
#    ports:
#      - "3000:3000"
#    env_file:
#      - 'grafana/env.grafana'
#    volumes:
#      - mycodo_grafana:/var/lib/grafana
#    depends_on:
#      - mycodo_influxdb

volumes:
  mycodo_home:
  mycodo_log:
  mycodo_influxdb:
  mycodo_grafana:
