name: Mycodo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install apt dependencies
        run: |
            sudo apt-get install -y libatlas-base-dev libboost-python-dev gawk git libffi-dev libi2c-dev nginx python3-dev python3-numpy sqlite3 swig
            sudo bash mycodo/scripts/upgrade_commands.sh update-packages
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          sudo bash mycodo/scripts/upgrade_commands.sh setup-virtualenv
          sudo bash mycodo/scripts/upgrade_commands.sh update-pip3
          sudo bash mycodo/scripts/upgrade_commands.sh update-pip3-packages
      - name: Test with pytest
        run: |
          cd mycodo && ../env/bin/pytest -W ignore::DeprecationWarning -s tests/software_tests
